### PR TITLE
refs #9044 - refactor mac test fix

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by lzap** [comment]
Going to [test] in a minute.

**Comment by lzap** [comment]
LGTM, the core change was backported into 1.7.3, so we need to assign it to 2.0.1. I need to check if it works with or without the patch in core (1.7.2 vs 1.7.3).

**Comment by lzap** [comment]
Tested on 1.7.2, fails on develop:

```
2015-03-04 10:46:55 [E] undefined method `ip' for #<PuppetFactParser:0x007fcfaddd29b0> (NoMethodError)
/home/lzap/work/foreman/app/models/host/base.rb:137:in `block in set_non_empty_values'
/home/lzap/work/foreman/app/models/host/base.rb:136:in `each'
/home/lzap/work/foreman/app/models/host/base.rb:136:in `set_non_empty_values'
/home/lzap/work/foreman/app/models/host/base.rb:129:in `populate_fields_from_facts'
/home/lzap/work/foreman_discovery/app/models/host/discovered.rb:102:in `populate_fields_from_facts'
/home/lzap/work/foreman/app/models/host/base.rb:106:in `import_facts'
/home/lzap/work/foreman_discovery/app/models/host/discovered.rb:92:in `import_facts'
/home/lzap/work/foreman_discovery/app/models/host/discovered.rb:84:in `import_host_and_facts'
```

**Comment by lzap** [comment]
Merged as 2fc226e
