### PR TITLE
Fixes #14637 - taxonomy to rules API added

### PR DESCRIPTION
**Pull request by shlomizadok**

### CODE REVIEW

**Comment by dLobatog** [comment]
@shlomizadok Please check out test failures - although currently there's a problem that's throwing more failures because of https://github.com/theforeman/foreman/pull/3574/files#diff-07cbb99bfdb4bed86ad02486bb5adde2R174

**Comment by lzap** [comment]
We actually have two issues:

```
undefined local variable or method `accessible_hostgroups'
```

PR is pending for this one, I'd like to merge it ASAP. Then:

```
undefined method `enable_orchestration!'
```

I have reported this one as http://projects.theforeman.org/issues/15645

Edit: @dLobatog created the same report a minute ago :-) Dupe of http://projects.theforeman.org/issues/15644 then.

**Comment by lzap** [comment]
@shlomizadok develop is green again, please rebase and also reword the commit message to `Fixes #14637 - taxonomy to rules API added` thank you!

**Comment by shlomizadok** [comment]
@lzap - Thanks. Rebased and reworded

File: test/functional/api/v2/discovery_rules_controller_test.rb [hunk 1]
```diff
@@ -48,6 +48,14 @@ class Api::V2::DiscoveryRulesControllerTest < ActionController::TestCase
     assert_response :success
   end
 
+  test "should update taxonomy for discovery rule" do
+    rule = FactoryGirl.create(:discovery_rule)
+    organization = FactoryGirl.create(:organization)
+    put :update, { :id => rule.to_param, :discovery_rule => { :organization_ids => [organization.id] } }
+    assert_response :success
+    assert_equal(rule.organization_id, organization.id)
```
Comment (lzap) [inline test/functional/api/v2/discovery_rules_controller_test.rb]:
```
  1) Error:
Api::V2::DiscoveryRulesControllerTest#test_0005_should update taxonomy for discovery rule:
NoMethodError: undefined method `organization_id' for #<DiscoveryRule:0x0055e20df64cb8>
Did you mean?  organization_ids
               organization_ids=
               organization_ids_was
               organizations
               organizations=
    /home/lzap/work/foreman_discovery/test/functional/api/v2/discovery_rules_controller_test.rb:56:in `block in <class:DiscoveryRulesControllerTest>'
```

Comment (shlomizadok) [inline test/functional/api/v2/discovery_rules_controller_test.rb]: Yeah, have a typo there... will fix soon

2016-07-21 11:24 GMT+03:00 Lukáš Zapletal notifications@github.com:

**Comment by dLobatog** [comment]
:+1: pending Jenkins

**Comment by dLobatog** [comment]
Merged as 2aea5501a3efeaea3cdd1e7ee99f170c2cd8311d, thanks @shlomizadok!
