### PR TITLE
Fixes #17585 - moved permission migration after override

### PR DESCRIPTION
**Pull request by lzap**
When upgrading Foreman from 1.11 to 1.13, this migration fails with.

```
undefined method `override=' for #<Filter:0x0000000e6f82c8>/opt/rh/sclo-ror42/root/usr/share/gems/gems/activemodel-4.2.5.1/lib/active_model/attribute_methods.rb:433:in `method_missing'
/usr/share/foreman/app/models/filter.rb:216:in `enforce_override_flag'
```

This patch makes sure the migration is triggered *after* the one in core that
is causing this (adding the override flag):

    db/migrate/20160818091420_add_override_flag_to_filter.rb

I considered using fake objects but it's quite complex code for this one and it
is not worth the effort (for an example see https://github.com/theforeman/foreman/blob/develop/db/migrate/20140219183343_migrate_permissions.rb - I'd need to implement all of these).

This will cause the migration to occur twice basically, but it is idempotent.
The permissions API no longer adds duplicities.

### CODE REVIEW

**Comment by lzap** [comment]
Don't merge, I screwed it up. Need to push.

**Comment by lzap** [comment]
Now it's correct. If you don't mind quick merge @dLobatog or @orrabin this is 6.3 QA upgrade blocker. Thanks!

**Comment by lzap** [comment]
I believe the failure is not related, develop broken :-(

**Comment by ehelms** [comment]
I wonder if this would be better done in a seed?

**Comment by lzap** [comment]
Plugins do this via lib/foreman_discovery/engine.rb actually and we have it there. The migration is only for existing roles.

File: db/migrate/20160818091421_add_missing_view_permissions2.rb [hunk 1]
```diff
@@ -0,0 +1,21 @@
+class AddMissingViewPermissions2 < ActiveRecord::Migration
+  def up
+    # this migration was renamed from 20160719124942_add_missing_view_permissions.rb
+    return if ActiveRecord::Migrator.get_all_versions.include?(20160719124942)
```
Comment (orrabin) [inline db/migrate/20160818091421_add_missing_view_permissions2.rb]: why not just check if the permissions exist in the list of permissions?

File: db/migrate/20160818091421_add_missing_view_permissions2.rb [hunk 2]
```diff
@@ -0,0 +1,21 @@
+class AddMissingViewPermissions2 < ActiveRecord::Migration
+  def up
+    default_permissions = Foreman::Plugin.find("foreman_discovery").default_roles
```
Comment (orrabin) [inline db/migrate/20160818091421_add_missing_view_permissions2.rb]: :+1: running this I found the list was missing view_locations which should be added.

File: db/migrate/20160818091421_add_missing_view_permissions2.rb [hunk 3]
```diff
@@ -0,0 +1,21 @@
+class AddMissingViewPermissions2 < ActiveRecord::Migration
```
Comment (orrabin) [inline db/migrate/20160818091421_add_missing_view_permissions2.rb]: Nitpick: please notice this now adds more then view permissions which is good because I had missing permissions in my discovery role but maybe change the name?

File: db/migrate/20160818091421_add_missing_view_permissions2.rb [hunk 4]
```diff
@@ -0,0 +1,21 @@
...
+  def up
+    default_permissions = Foreman::Plugin.find("foreman_discovery").default_roles
+    ["Discovery Reader", "Discovery Manager"].each do |role_name|
+      role = Role.find_by_name(role_name) || next
+      puts "Processing #{role}"
+      default_permissions[role_name].each do |permission|
+        unless role.permission_names.include?(permission.to_sym)
+          puts "Adding permission #{permission}"
```
Comment (orrabin) [inline db/migrate/20160818091421_add_missing_view_permissions2.rb]: do we want to actually show it when the migration is running or just add it to logs?

**Comment by lzap** [comment]
Renamed, removed the puts statements.

**Comment by orrabin** [comment]
@lzap looks good. Ready to merge when tests are green.

**Comment by orrabin** [comment]
thanks @lzap!

**Comment by lzap** [comment]
Many thanks!
